version: '3.8'

services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    restart: unless-stopped
    deploy:
      placement:
        constraints:
          - node.role == manager
    entrypoint: ["/bin/sh", "-c", "export PASS=$$(cat /run/secrets/transmission_password); source /init"]
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - USER=transmission
    volumes:
      - transmission:/config
      - shared:/downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    networks:
      - proxy
    secrets:
      - transmission_password

secrets:
  transmission_password:
    external: true

volumes:
  shared:
    external: true
  transmission:
    external: true

networks:
  proxy:
    external: true
