version: '3.8'

services:
  mariadb:
    image: mariadb:lts
    restart: unless-stopped:3
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/mariadb_password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - databases
    secrets:
      - mariadb_password

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped:3
    deploy:
      placement:
        constraints:
          - node.role == manager
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/postgres_password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    networks:
      - databases
    secrets:
      - postgres_password

  redis:
    image: redis:alpine
    restart: unless-stopped:3
    deploy:
      placement:
        constraints:
          - node.role == manager
    command: --save 60 1 --loglevel warning
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - redis_data:/data
    networks:
      - databases

  adminer:
    image: adminer:latest
    restart: unless-stopped
    networks:
      - nginx
      - databases

secrets:
  mariadb_password:
    external: true
  postgres_password:
    external: true

volumes:
  mariadb_data:
    external: true
  postgres_data:
    external: true
  redis_data:
    external: true

networks:
  databases:
    external: true
  nginx:
    external: true

