#!/bin/bash

docker run --rm -it \
  \
  -v backup_config:/config/ \
  -v backup_data:/mnt/volumes/backup_data \
  -v /tmp:/tmp \
  -v /var/run/docker.sock:/var/run/docker.sock \
  \
  -v nginx_data:/mnt/volumes/nginx_data/ \
  -v nginx_config:/mnt/volumes/nginx_config/ \
  -v nginx_letsencrypt:/mnt/volumes/nginx_letsencrypt/ \
  -v transmission_config:/mnt/volumes/transmission_config/ \
  -v samba_data:/mnt/volumes/samba_data/ \
  -v mariadb_data:/mnt/volumes/mariadb_data/ \
  -v postgres_data:/mnt/volumes/postgres_data/ \
  -v firefly_upload:/mnt/volumes/firefly_upload/ \
  -v nextcloud_config:/mnt/volumes/nextcloud_config/ \
  -v authentik_media:/mnt/volumes/authentik_media/ \
  -v authentik_certs:/mnt/volumes/authentik_certs/ \
  -v authentik_templates:/mnt/volumes/authentik_templates/ \
  -v jellyfin_config:/mnt/volumes/jellyfin_config/ \
  -v lidarr_config:/mnt/volumes/lidarr_config/ \
  -v radarr_config:/mnt/volumes/radarr_config/ \
  -v prowlarr_config:/mnt/volumes/prowlarr_config/ \
  \
  --name backup backup:local $@
