#!/bin/bash

if ! type node &> /dev/null; then
  echo "This script requires nodejs to be installed. Please install it and try again."
  exit 1
fi

main_commnad=$(node index.js)

bash -c "$main_commnad  $@"