services:
  traefik:
    image: "traefik:v3.1"
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.letencrypt.acme.httpchallenge=true"
      - "--certificatesResolvers.letencrypt.acme.httpChallenge.entryPoint=web"
      - "--certificatesResolvers.letencrypt.acme.email=f.rusanov@gmail.com"
      - "--certificatesResolvers.letencrypt.acme.storage=/certs/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik-certs:/certs
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.rusanov.cloud`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.tls.certresolver=letencrypt"
      - "traefik.http.routers.traefik.service=api@internal"

volumes:
  traefik-certs:
    external: true

networks:
  proxy:
    external: true
