services:
  traefik:
    image: "traefik:v3.2"
    command:
      - "--configFile=/etc/traefik/config.yml"
    env_file:
      - ./.env
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - traefik_certs:/etc/traefik/acme
      - ./dynamic:/etc/traefik/dynamic
      - ./config.yaml:/etc/traefik/config.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - proxy
    labels:
      - "forceUpdate=2024.12.22-21:16"

volumes:
  traefik_certs:
    external: true

networks:
  proxy:
    external: true
