version: '3.8'

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    restart: unless-stopped:3
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - prowlarr_config:/config
    networks:
      - nginx
  
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    restart: unless-stopped:3
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - lidarr_config:/config
      - shared:/shared
      - shared:/downloads
    networks:
      - nginx

  readarr:
    image: lscr.io/linuxserver/readarr:latest
    restart: unless-stopped:3
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - readarr_config:/config
      - shared:/shared
      - shared:/downloads
    networks:
      - nginx

volumes:
  shared:
    external: true
  prowlarr_config:
    external: true 
  lidarr_config:
    external: true 
  readarr_config:
    external: true 

networks:
  nginx:
    external: true

