version: "3"

services:
  wiki:
    image: ghcr.io/requarks/wiki:2
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.wiki.loadbalancer.server.port=3000"
        - "traefik.http.routers.wiki.rule=Host(`wiki.home`)"
        - "traefik.http.routers.wiki.entrypoints=web"
    environment:
      DB_TYPE: postgres
      DB_HOST: databases_postgres
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS_FILE: /run/secrets/postgres_password
      DB_NAME: wikijs
    restart: unless-stopped
    secrets:
      - postgres_password
    networks:
      - proxy
      - databases

secrets:
  postgres_password:
    external: true

networks:
  proxy:
    external: true
  databases:
    external: true
