version: "3.8"

services:
  app:
    image: lscr.io/linuxserver/jellyfin:10.8.13
    restart: unless-stopped
    deploy:
      # # TODO: must be done only after mirgation to Postgres
      # mode: replicated
      # replicas: 2
      # restart_policy:
      #   condition: on-failure
      #   delay: 5s
      #   max_attempts: 3
      #   window: 120s
      # update_config:
      #   parallelism: 1
      #   delay: 10s
      #   order: stop-first
      placement:
        constraints:
          - node.role == manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:jellyfin-rffmpeg
    volumes:
      - jellyfin_config:/config
      - shared:/data/shared
    networks:
      - nginx

volumes:
  shared:
    external: true
  jellyfin_config:
    external: true

networks:
  nginx:
    external: true
