version: '3.8'

services:
  app:
    image: lscr.io/linuxserver/jellyfin:latest
    restart: unless-stopped:3
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - DOCKER_MODS=linuxserver/mods:jellyfin-amd
    volumes:
      - jellyfin_config:/config
      - shared:/data/shared
    devices:
      - /dev/dri:/dev/dri
      - /dev/kfd:/dev/kfd
    networks:
      - nginx

volumes:
  shared:
    external: true
  jellyfin_config:
    external: true 

networks:
  nginx:
    external: true

