services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - GENERIC_TIMEZONE=Asia/Bangkok
      - TZ=Asia/Bangkok
      - N8N_EDITOR_BASE_URL=https://n8n.rusanov.cloud
      - WEBHOOK_URL=https://n8n.rusanov.cloud
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - proxy
      - databases
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.n8n.loadbalancer.server.port=5678"
        - "traefik.http.routers.n8n.rule=Host(`n8n.rusanov.cloud`)"
        - "traefik.http.routers.n8n.entrypoints=websecure"
        - "traefik.http.routers.n8n.tls.certresolver=default-acme"
        - "traefik.docker.network=proxy"

volumes:
  n8n_data:
    external: true

networks:
  proxy:
    external: true
  databases:
    external: true
