services:
  prometheus:
    image: prom/prometheus:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    ports:
      - 9090:9090
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - monitoring
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - forceUpdate=2024.12.07_22.41

  node-exporter:
    image: prom/node-exporter
    deploy:
      mode: global
      placement:
        constraints:
          - node.platform.os == linux
    hostname: "{{.Node.Hostname}}"
    networks:
      - monitoring
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/rootfs"
      - "--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    deploy:
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis

  redis:
    image: redis:latest
    networks:
      - monitoring
    deploy:
      placement:
        constraints:
          - node.role == manager

  grafana:
    image: grafana/grafana-oss:11.4.0
    ports:
      - 3002:3000
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.http.routers.grafana.rule=Host(`grafana.rusanov.cloud`)"
        - "traefik.http.routers.grafana.entrypoints=websecure"
        - "traefik.http.routers.grafana.tls.certresolver=default-acme"
      placement:
        constraints:
          - node.role == manager
    networks:
      - monitoring
      - proxy
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  prometheus_data:
    external: true
  grafana_data:
    external: true

networks:
  monitoring:
    external: true
  proxy:
    external: true
